/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as BecomeAConsultantRouteImport } from './routes/become-a-consultant'
import { Route as AgricultureRouteImport } from './routes/agriculture'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAConsultantRoute = BecomeAConsultantRouteImport.update({
  id: '/become-a-consultant',
  path: '/become-a-consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultureRoute = AgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agriculture': typeof AgricultureRoute
  '/become-a-consultant': typeof BecomeAConsultantRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/partnerships': typeof PartnershipsRoute
  '/publications': typeof PublicationsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agriculture': typeof AgricultureRoute
  '/become-a-consultant': typeof BecomeAConsultantRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/partnerships': typeof PartnershipsRoute
  '/publications': typeof PublicationsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agriculture': typeof AgricultureRoute
  '/become-a-consultant': typeof BecomeAConsultantRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/partnerships': typeof PartnershipsRoute
  '/publications': typeof PublicationsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/transport': typeof TransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agriculture'
    | '/become-a-consultant'
    | '/construction'
    | '/contact'
    | '/education'
    | '/events'
    | '/gallery'
    | '/partnerships'
    | '/publications'
    | '/services'
    | '/team'
    | '/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agriculture'
    | '/become-a-consultant'
    | '/construction'
    | '/contact'
    | '/education'
    | '/events'
    | '/gallery'
    | '/partnerships'
    | '/publications'
    | '/services'
    | '/team'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agriculture'
    | '/become-a-consultant'
    | '/construction'
    | '/contact'
    | '/education'
    | '/events'
    | '/gallery'
    | '/partnerships'
    | '/publications'
    | '/services'
    | '/team'
    | '/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgricultureRoute: typeof AgricultureRoute
  BecomeAConsultantRoute: typeof BecomeAConsultantRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PublicationsRoute: typeof PublicationsRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-consultant': {
      id: '/become-a-consultant'
      path: '/become-a-consultant'
      fullPath: '/become-a-consultant'
      preLoaderRoute: typeof BecomeAConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agriculture': {
      id: '/agriculture'
      path: '/agriculture'
      fullPath: '/agriculture'
      preLoaderRoute: typeof AgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgricultureRoute: AgricultureRoute,
  BecomeAConsultantRoute: BecomeAConsultantRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  PartnershipsRoute: PartnershipsRoute,
  PublicationsRoute: PublicationsRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
